version: "3.8"

services: 
  frontend:
    depends_on:
      backend:
        condition: service_started
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports: 
      - 5173:5173
    networks: 
      - private
      - public
    secrets:
      - my_certificate

  backend:
    depends_on:
      database:
        condition: service_started
      cache:  
        condition: service_started
    build: 
      context: ./backend
      dockerfile: Dockerfile
      target: dev
    command: npm run start:dev
    ports: 
      - 3000:3000
    environment: 
      DB_USERNAME: user
      DB_PASSWORD: password
    networks: 
      - private
  
  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks: 
      - private
    volumes:
      - db-data:/var/lib/mysql
    
  cache:
    image: redis:latest
    ports:
      - 6380:6379
    networks:
      - private
    volumes:
      - cache-data:/data


secrets:
  my_certificate:
    file: ./basic-certificate-cert

volumes:
  db-data:
  cache-data:

networks:
  public:
  private:
    internal: true
  